CREATE TABLE db (
    id INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    email2 VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    password2 VARCHAR(255) NOT NULL
);
